variable "proxmox_host" {
default = "http://192.168.1.10:8006"
}

variable "proxmox_host_ssh" {
default = "192.168.1.10"
}

variable "proxmox_node_name" {
default = "LAB"
}

variable "proxmox_api_user" {
default = "root@pam"
}

variable "template_name" {
default = "ubuntu-22-{{ isotime \"2023-11-16T15-04-05\" }}"
}

variable "template_description" {
default = "Ubuntu 22.4, generated by packer on {{ isotime \"2006-01-02T15:04:05Z\" }}"
}

variable "ssh_fullname" {
default = "ubuntu"
}

variable "ssh_username" {
default ="ubuntu"
}

variable "hostname" {
default = "ubuntu-22-04-cloudinit"
}
variable "vmid" {
default = "1010"
}

variable "locale" {
default = "en_US"
}
variable "cores" {
default = "2"
}
variable "sockets" {
default = "1"
}
variable "memory" {
default = "2048"
}
variable "disk_size" {
default = "8G"
}
variable "datastore" {
default = "local-lvm"
}
variable "datastore_type" {
default = "directory"
}
variable "iso" {
default = "local:iso/ubuntu-22.04.3-live-server-amd64.iso"
}

variable "boot_command_prefix" {
default = ""
}


variable "ssh_password" {
default = "PASpas123!@#"
}

variable "proxmox_api_password" {
default = "VIACMD"
}

